In [96]:
import os
import plotly
import colorlover as cl
from IPython.display import HTML
import plotly.io as pio
pio.renderers.default = "browser"
import chart_studio.plotly as py
import plotly.graph_objs as go
import matplotlib.pyplot as plt
from plotly import tools
import pandas as pd
import numpy as np
import seaborn as sb
from collections import OrderedDict
from plotly.subplots import make_subplots
#plotly.tools.set_credentials_file(username='amcdonne', api_key=apiKey)
#plotly.tools.set_config_file(world_readable=False, sharing='private')
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 1000)
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
pd.options.display.float_format = '{:.2f}'.format

In [11]:
data_dict_path = 'C:/Users/austi/Documents/Github_Repos/Imperial_Applied_Project/Detroit/Saved_Data/Test_Data_Dict/'
#saved_data_html_path = 'C:/Users/austi/Documents/Github_Repos/Imperial_Applied_Project/Detroit/Saved_Data/HTML/'

#csv_data_path = 'C:/Users/austi/Documents/Github_Repos/Imperial_Applied_Project/Detroit/Saved_Data/CSV_Data/'
#file_name = 'FULLY_CLEANED_Aggregated_Home_Data_8.27.2019.csv'

pkl_dataframes_path = 'C:/Users/austi/Documents/Github_Repos/Imperial_Applied_Project/Detroit/Saved_Data/Pickle_DataFrames/'
pkl_file_name = 'Fully_Cleaned_House_Data_8.27.2019.pkl'
os.chdir(pkl_dataframes_path)
#pd.DataFrame.to_csv(data, path_or_buf= csv_data_path + file_name)
data = pd.read_pickle(pkl_dataframes_path+pkl_file_name)
data = data.set_index('House_Id')

In [33]:
data.head().T

House_Id                                            2096667469_zpid                         2090771520_zpid                          2085043646_zpid                       88380061_zpid                   2083788163_zpid
Bedrooms                                                       2.00                                    2.00                                     1.00                                2.00                              3.00
Total_Interior_Livable_Area                                 1182.00                                 1250.00                                   840.00                             2300.00                           2450.00
Number_Of_Appliances                                              8                                       8                                        0                                   0                                 4
Bathrooms                                                      2.00                                    2.00                                     1.00                                3.00                              4.00
Stories                                                        1.00                                    1.00                                     0.00                                0.00                              0.00
Home_Type                                                 TOWNHOUSE                               TOWNHOUSE                                    CONDO                               CONDO                         TOWNHOUSE
Year_Built                                                  1905.00                                 1905.00                                  1920.00                             2002.00                           2019.00
New_Construction                                               0.00                                    0.00                                     0.00                                0.00                              0.00
Hoa_Fee                                                         254                                     254                                      292                                   0                               461
Average_School_Rating                                          0.00                                    0.00                                     0.00                                0.00                              0.00
Average_School_Distance                                        0.00                                    0.00                                     0.00                                0.00                              0.00
School_Listed_Binary                                          False                                   False                                    False                               False                             False
Time_On_Zillow                                                55.00                                   54.00                                   130.00                                0.00                             47.00
Price                                                     549000.00                               584900.00                                297000.00                           329467.00                        1600000.00
Zestimate                                                 507316.00                               542388.00                                283500.00                           433510.00                               NaN
Number_Of_Photos                                                 21                                      20                                       26                                   3                                29
Address                      104 Edmund Pl APT 2, Detroit, MI 48201  104 Edmund Pl APT 3, Detroit, MI 48201  112 Watson St # 23/4, Detroit, MI 48201  118 Adelaide St, Detroit, MI 48201  248 Alfred St, Detroit, MI 48201
Views                                                           343                                     476                                      300                                 264                             1,303
Longitude                                                    -83.05                                  -83.05                                   -83.06                              -83.05                            -83.05
Latitude                                                      42.34                                   42.34                                    42.35                               42.34                             42.34
Saves                                                             5                                       6                                        2                                   2                                12
Price_Cut                                                      0.00                                    0.00                                  2000.00                                0.00                              0.00
Price_sqft                                                   464.00                                  468.00                                   354.00                                0.00                            653.00
Garage_Spaces                                                  0.00                                    1.00                                     0.00                                1.00                              0.00
Lot_Size                                                       0.11                                    0.11                                     0.11                                0.04                              0.11
Tax_Assessed_Value                                        277972.05                               296149.10                                150378.32                            18400.00                         810118.91
Annual_Tax_Amount                                          12162.32                                12957.63                                  6579.62                              211.00                          35445.74
Price_Unknown_Binary                                          False                                   False                                    False                               False                             False
Calculated_Price_Sqft                                        464.47                                  467.92                                   353.57                              143.25                            653.06
Store_Name                                       Whole Foods Market                      Whole Foods Market                       Whole Foods Market                             NO DATA                Whole Foods Market
Store_Price_Level                                              3.00                                    3.00                                     3.00                                1.00                              3.00
Store_Listed_Binary                                            True                                    True                                     True                               False                              True
Parking_Features_Cat                                ATTACHED GARAGE                         ATTACHED GARAGE                                  NO DATA                     ATTACHED GARAGE                   ATTACHED GARAGE
Heating_Cat                                              FORCED AIR                              FORCED AIR                                  NO DATA                          FORCED AIR                        FORCED AIR
Cooling_Cat                                                 CENTRAL                                 CENTRAL                                  NO DATA                             NO DATA                           CENTRAL
Basement_Cat                                                NO DATA                                 NO DATA                                  NO DATA                             NO DATA                           NO DATA
Roof_Cat                                                    NO DATA                                 NO DATA                                  NO DATA                             NO DATA                           NO DATA
Structure_Type_Cat                                        VICTORIAN                                 NO DATA                                     LOFT                             NO DATA                           NO DATA
Construction_Materials_Cat                                    BRICK                                   BRICK                                  NO DATA                             NO DATA                             OTHER
Exterior_Features_Cat                                         BRICK                                   BRICK                                  NO DATA                               OTHER                             OTHER
Architectural_Style_Cat                                    HISTORIC                                HISTORIC                                  NO DATA                             NO DATA                           NO DATA
Price_Bin                                                    $300k+                                  $300k+                            $180k - $300k                              $300k+                            $300k+

In [18]:
data.Price.describe()

count      3304.00
mean     140431.60
std      292008.21
min        1000.00
25%       30000.00
50%       54900.00
75%      129900.00
max     6499999.00
Name: Price, dtype: float64

#### Charting Functions

In [46]:
#import plotly.io as pio
#pio.renderers.default = "browser"

trace1 = go.Histogram(
    name='Latitude',
    x=data.Latitude,
    opacity=0.75,
    autobinx=True,
    #xbins=dict(start=defaultedMin, end=defaultedMax, size=2),
)
plot_data = [trace1]
layout = go.Layout(barmode='overlay')
fig = go.Figure(data=plot_data, layout=layout)
fig.show()
#Saving Down the File to Plotly Charts
#py.iplot(fig, filename='House_pricing_histogram', sharing='private')

#### Bin Cutting

In [56]:
price_bins = [0, 20000, 30000, 40000, 60000, 100000, 180000, 300000, 50000000]

price_bin_names = ['$0 - $20k', '$20k - $30k', '$30k - $40k', '$40k - $60k', '$60k - $100k', '$100k - $180k', '$180k - $300k', '$300k+']
data['Price_Bin'] = pd.cut(data.Price, bins=price_bins, labels=price_bin_names, right=False)
#data.Price_Bin = data.Price_Bin.cat.add_categories('No Score').fillna('No Score')
data.Price_Bin.value_counts()

$40k - $60k      588
$60k - $100k     468
$100k - $180k    445
$30k - $40k      405
$0 - $20k        401
$20k - $30k      387
$300k+           381
$180k - $300k    229
Name: Price_Bin, dtype: int64

#### Grouping & Stratification

In [70]:
grouping_dict = {
    'Bedrooms': ['mean'],
    'Bathrooms': ['mean'],
    'Calculated_Price_Sqft': ['mean'],
    'Total_Interior_Livable_Area': ['mean'],
    'Hoa_Fee': ['mean'],
    'Year_Built': ['mean'],
    'Average_School_Rating': ['mean'],
    'Store_Price_Level': ['mean'],
    'Longitude': ['mean'],
    'Latitude': ['mean']
    
    
}
data.groupby(['Price_Bin']).agg(grouping_dict)

              Bedrooms Bathrooms Calculated_Price_Sqft Total_Interior_Livable_Area Hoa_Fee Year_Built Average_School_Rating Store_Price_Level Longitude Latitude
                  mean      mean                  mean                        mean    mean       mean                  mean              mean      mean     mean
Price_Bin
$0 - $20k         2.57      1.35                 12.32                     1269.63   39.66    1935.94                  0.00              0.84    -83.08    42.40
$20k - $30k       2.42      1.44                 24.21                     1276.17    4.39    1937.45                  0.08              0.84    -83.10    42.40
$30k - $40k       2.59      1.37                 32.36                     1193.91  104.49    1937.24                  0.06              0.84    -83.10    42.40
$40k - $60k       2.74      1.54                 43.05                     1298.19    8.68    1938.48                  0.16              0.82    -83.11    42.40
$60k - $100k      2.55      1.77                 60.86                     1469.06  217.62    1939.41                  0.67              0.77    -83.13    42.40
$100k - $180k     2.95      1.98                 92.48                     1598.96   35.31    1937.89                  1.41              0.78    -83.11    42.40
$180k - $300k     2.77      2.39                158.25                     1867.02  129.47    1943.69                  1.89              0.83    -83.04    42.39
$300k+            3.50      4.65                235.80                     3646.14  165.81    1950.65                  1.82              1.09    -83.01    42.38

In [ ]:
percent_total = lambda x: (x.count() / len(data.index))*100
percent_total.__name__ = 'Percent of Total'
def lat_long():
    def _lat_long(x):
        np.array2string(np.average(x), formatter={'float_kind':lambda x: "%.5f" % x})
    _lat_long.__name__ = f'Average'
    return _lat_long

def avg(percent_format):
    val = ''
    def _avg(x):
        if percent_format:
            return round(np.average(x)*100, 2)
        return round(np.average(x), 2)
    if percent_format:
        val = ' (%)'
    _avg.__name__ = f'Average Value{val}'
    return _avg

grouping_dict = {
    'obligorCreditScore': [avg(percent_format=False), 'count', percent_total],
    'paymentToIncomePercentage': [avg(percent_format=True), 'count', percent_total]
    
}

d_df.groupby(['CS_Bucket','obligorEmploymentVerificationCode']).agg(grouping_dict)

#### Paracoords Chart

In [ ]:
'''
Para-Coords Chart
'''
total_df = pd.concat([pd_df, d_df])
total_df['CS_cat_codes'] = total_df.CS_Bucket.cat.codes

trace1 = go.Parcoords(

    opacity=.7,
    dimensions = list([
        dict(tickvals = [1, 4],
             ticktext = ['Paid Down', 'Defaulted'],
             label = 'Result', values = total_df.zeroBalanceCode),
        dict(tickvals = [1, 2, 3],
             ticktext = ['Stated, Not Verified', 'Stated, Verified', 'Stated, 3rd Party Verified'],
             label = 'Employment Verification', values = total_df.obligorEmploymentVerificationCode),
         dict(tickvals = [5, 0, 1, 2, 3, 4],
             ticktext = ['No Score', '300 - 579', '580 - 669', '670 - 739', '740 - 799', '800+'],
             label = 'CS-Bucket', values = total_df.CS_cat_codes),
        dict(range = [np.min(total_df.paymentToIncomePercentage), np.max(total_df.paymentToIncomePercentage)],
             label = 'PTI', values = total_df.paymentToIncomePercentage),
        
        
    ]),

)
layout = go.Layout(
    title='All Loans',
    hovermode = 'closest',
)

fig = go.Figure(data = [trace1], layout = layout)
py.iplot(fig, filename = 'Total_paid_down_and_defaulted-paracoords', sharing='private')

#### Single Chart - Multiple Lines Graphed

In [93]:
#temp = data[data.Price_Bin == '$40k - $60k']
temp = data.sort_values(by='Latitude')
#temp = temp[temp.Price_Bin == '$0 - $20k']

In [125]:
def long_lat_price_scatter(data, plot_name):
    trace = go.Scatter(
        x = data.Latitude,
        y = data.Longitude,
        name = plot_name,
        mode='markers',
        opacity = 0.7,
        marker=dict(
            size=6,
            showscale=False,
            colorscale='RdYlBu',#'Blues',
            #reversescale=True,
            color=data.Price,
            #color = '#2ca02c', #set color equal to a variable
        )
    )
    return trace

In [129]:
from plotly.subplots import make_subplots
price_plot_titles = [
    '$0 - $20k',
    '$20k - $30k',
    '$30k - $40k',
    '$40k - $60k',
    '$60k - $100k',
    '$100k - $180k',
    '$180k - $300k',
    '$300k+',
]

fig = make_subplots(rows=4, cols=2)#, shared_yaxes=True, shared_xaxes=True)

row_val=1
col_val=1
for bucket in price_plot_titles:
    #print(bucket)
    if row_val > 4:
        col_val+=1
        row_val=1
    temp = data[data.Price_Bin == bucket]
    fig.add_trace(long_lat_price_scatter(temp, bucket), row=row_val, col=col_val)
    row_val+=1

In [130]:
fig.show()

In [95]:
trace_lat = go.Scatter(
    x = temp.Latitude,
    y = temp.Longitude,
    name = 'Latitude, Longitude',
    mode='markers',
    opacity = 0.7,
    marker=dict(
        size=6,
        showscale=True,
        colorscale='RdYlBu',#'Blues',
        #reversescale=True,
        color=temp.Price,
        #color = '#2ca02c', #set color equal to a variable
    )
)
plot_data = [trace_lat]
layout = go.Layout(
    title='Latitude vs Longitude',
    hovermode = 'closest',
    xaxis= dict(title='Latitude'),#, tickformat='.0%'),
    yaxis= dict(title='Longitude')
)
fig = go.Figure(data=plot_data, layout=layout)

fig.show()
#fig = go.Figure(data=data, layout=layout)
#py.iplot(fig, filename='Defaulted_APR_CS_Total', sharing = 'private')

In [ ]:
trace_long = go.Scatter(
    x = data.Longitude.sort_values().values,
    name = 'Longitude',
    mode='markers',
    opacity = 0.7,
    marker=dict(
        size=6,
        #showscale=True,
        #colorscale='Blues',
        #reversescale=True,
        #color=defaulted['obligorCreditScore'],
        color = '#2ca02c', #set color equal to a variable
    )
)
plot_data = [trace_long]
layout = go.Layout(
    title='Longitude vs Price',
    hovermode = 'closest',
    xaxis= dict(title='Longitude'),#, tickformat='.0%'),
    yaxis= dict(title='Number of Homes')
)
fig = go.Figure(data=plot_data, layout=layout)

#fig.show()
#fig = go.Figure(data=data, layout=layout)
#py.iplot(fig, filename='Defaulted_APR_CS_Total', sharing = 'private')

In [ ]:
#defaulted.sort_values(by=['originalInterestRatePercentage'], inplace=True) Prime 661-780 Super Prime 781-850
#cl.scales['3']['div']['BuGn'][2]

trace7 = go.Scattergl(
    x = dataDict['defaulted']['creditScore']['Super Prime 781-850+'].sort_values(by=['originalInterestRatePercentage'])['originalInterestRatePercentage'],
    name = 'Super Prime 781-850+',
    mode='markers',
    opacity = 0.7,
    marker=dict(
        size=6,
        #showscale=True,
        #colorscale='Blues',
        #reversescale=True,
        #color=defaulted['obligorCreditScore'],
        color = '#2ca02c', #set color equal to a variable
    )
)

trace8 = go.Scattergl(
    x = dataDict['defaulted']['creditScore']['Prime 661-780'].sort_values(by=['originalInterestRatePercentage'])['originalInterestRatePercentage'],
    name = 'Prime 661-780',
    mode='markers',
    opacity = 0.7,
    marker=dict(
        size=6,
        #showscale=True,
        #colorscale='Blues',
        #reversescale=True,
        #color=defaulted['obligorCreditScore'],
        color = '#bcbd22', #set color equal to a variable
    )
)

trace9 = go.Scattergl(
    x = dataDict['defaulted']['creditScore']['Nonprime 601-660'].sort_values(by=['originalInterestRatePercentage'])['originalInterestRatePercentage'],
    name = 'Nonprime 601-660',
    mode='markers',
    opacity = 0.7,
    marker=dict(
        size=6,
        #showscale=True,
        #colorscale='Blues',
        #reversescale=True,
        #color=defaulted['obligorCreditScore'],
        color = '#1f77b4', #set color equal to a variable
    )
)
trace10 = go.Scattergl(
    x = dataDict['defaulted']['creditScore']['Subprime 501-600'].sort_values(by=['originalInterestRatePercentage'])['originalInterestRatePercentage'],
    name = 'Subprime 501-600',
    mode='markers',
    opacity = 0.7,
    marker=dict(
        size=6,
        #showscale=True,
        #colorscale='Blues',
        #reversescale=True,
        #color=defaulted['obligorCreditScore'],
        color = '#d62728', #set color equal to a variable
    )
)
trace11 = go.Scattergl(
    x = dataDict['defaulted']['creditScore']['Deep Subprime 0-500'].sort_values(by=['originalInterestRatePercentage'])['originalInterestRatePercentage'],
    name = 'Deep Subprime 0-500',
    mode='markers',
    opacity = 0.7,
    marker=dict(
        size=6,
        #showscale=True,
        #colorscale='Blues',
        #reversescale=True,
        #color=defaulted['obligorCreditScore'],
        color = '#ff7f0e', #set color equal to a variable
    )
)
trace12 = go.Scattergl(
    x = dataDict['defaulted']['creditScore']['No Score'].sort_values(by=['originalInterestRatePercentage'])['originalInterestRatePercentage'],
    name = 'No Score',
    mode='markers',
    opacity = 0.7,
    marker=dict(
        size=6,
        #showscale=True,
        #colorscale='Blues',
        #reversescale=True,
        #color=defaulted['obligorCreditScore'],
        color = '#e377c2', #set color equal to a variable
    )
)

data = [trace7, trace8, trace9, trace10, trace11, trace12]
#total = go.Figure(data=data)
'''fig = tools.make_subplots(rows=3, cols=2, subplot_titles=('Super Prime<br>781-850+', 'Prime<br>661-780',
                                                          'Nonprime<br>601-660', 'Subprime<br>501-600',
                                                          'Deep Subprime<br>0-500', 'No Score')
                         )

fig.append_trace(trace7, 1, 1)
fig.append_trace(trace8, 1, 2)
fig.append_trace(trace9, 2, 1)
fig.append_trace(trace10, 2, 2)
fig.append_trace(trace11, 3, 1)
fig.append_trace(trace12, 3, 2)

fig['layout']['xaxis'].update(dict(tickformat='.0%'))
fig['layout']['xaxis2'].update(dict(tickformat='.0%'))
fig['layout']['xaxis3'].update(dict(tickformat='.0%'))
fig['layout']['xaxis4'].update(dict(tickformat='.0%'))
fig['layout']['xaxis5'].update(dict(tickformat='.0%'))
fig['layout']['xaxis6'].update(dict(tickformat='.0%'))

fig['layout'].update(showlegend=False, height=800, width=1300, title='Defaulted Loans: APR vs Credit Score')
'''
layout = go.Layout(
    title='Defaulted APR Split by Credit Score Bucket',
    hovermode = 'closest',
    xaxis= dict(title='APR', tickformat='.0%'),
    yaxis= dict(title='Number of Loans')
)
fig = go.Figure(data=data, layout=layout)


#fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='Defaulted_APR_CS_Total', sharing = 'private')

#### Histograms

In [ ]:
trace1 = go.Histogram(
    name='Paid Down',
    x=paidDown['obligorCreditScore'][paidDown['obligorCreditScore']>=300],
    opacity=0.75,
    autobinx=False,
    xbins= dict(start=paidDownMin, end=paidDownMax, size=2),
)

trace2 = go.Histogram(
    name='Defaulted',
    x=defaulted['obligorCreditScore'][defaulted['obligorCreditScore']>=300],
    opacity=0.75,
    autobinx=False,
    xbins=dict(start=defaultedMin, end=defaultedMax, size=2),
)
data = [trace1, trace2]
layout = go.Layout(barmode='overlay')
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='PaidDown_Defaulted_Overlay_Histogram', sharing='private')